#! /usr/bin/env python
# encoding: utf-8


bld.program(
    features = 'cxx',
    source   = ['fifi_tests.cpp'] + bld.path.ant_glob('src/*.cpp'),
    target   = 'fifi_tests',
    use      = ['gtest', 'fifi'])
