#! /usr/bin/env python
# encoding: utf-8


bld.stlib(features = 'cxx',
          source   = bld.path.ant_glob('**/*.cpp'),
          target = 'fifi',
          use    = ['FIFI_SIMD',
                    'boost_includes', 'sak_includes', 'sak', 'cpuid'],
          export_includes = ['..'])


# We want to make sure we can still build the library without any specific flags
bld.stlib(features = 'cxx',
          source   = bld.path.ant_glob('**/*.cpp'),
          target = 'fifi_no_dispatch',
          use    = ['boost_includes', 'sak_includes', 'sak', 'cpuid'],
          export_includes = ['..'])
